trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ASPNETCORE_ENVIRONMENT: 'Development'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: >
          /p:DeployOnBuild=true
          /p:WebPublishMethod=Package
          /p:PackageAsSingleFile=true
          /p:SkipInvalidConfigurations=true
          /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip"
          /p:DeployIisAppPath="Default Web Site"
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(build.artifactStagingDirectory)'
        Contents: '**/*.zip'
        TargetFolder: '$(build.artifactStagingDirectory)/drop'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactStagingDirectory)/drop'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployToVM
    environment: development
    strategy:
      runOnce:
        deploy:
          steps:

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: WindowsMachineFileCopy@2
            inputs:
              SourcePath: '$(System.ArtifactsDirectory)\drop\WebApp.zip'
              MachineNames: 'your-vm-ip'
              AdminUserName: 'your-vm-user'
              AdminPassword: '$(vmPassword)'  # Secure pipeline variable
              TargetPath: 'C:\inetpub\wwwroot\MyApp'

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                # Set environment variable for IIS
                [System.Environment]::SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", "Development", "Machine")

                # Unzip and deploy
                Expand-Archive -Path 'C:\inetpub\wwwroot\MyApp\WebApp.zip' -DestinationPath 'C:\inetpub\wwwroot\MyApp' -Force
                
                # Restart IIS
                iisreset
